### ISSUE TITLE
Seed found that claims exit with error, but does not throw?

### ISSUE THREAD

**Issue by bradmarder** [jakobbotsch/Fuzzlyn#12]
Hi Jakob again! No idea how to describe this one, I really don't know what is going on here. Both the reduced program and original execute without errors for me.

```c#
// Generated by Fuzzlyn v1.5 on 2022-03-29 02:23:41
// Run on X64 Windows
// Seed: 9461539929073564863
// Reduced from 248.4 KiB to 0.9 KiB in 00:02:02
// Exits with error:
// Unhandled exception. System.ArgumentException: Cannot bind to the target method because its signature is not compatible with that of the delegate type.
//    at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
//    at Fuzzlyn.ExecutionServer.Program.<RunPairAsync>g__RunAndGetResultAsync|1_0(Byte[] bytes, <>c__DisplayClass1_0&) in C:\Fuzzlyn\Fuzzlyn.ExecutionServer\Program.cs:line 115
//    at Fuzzlyn.ExecutionServer.Program.RunPairAsync(AssemblyLoadContext alc, ProgramPair pair) in C:\Fuzzlyn\Fuzzlyn.ExecutionServer\Program.cs:line 86
//    at Fuzzlyn.ExecutionServer.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\Fuzzlyn\Fuzzlyn.ExecutionServer\Program.cs:line 53
// 
public class Program
{
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }

    public static void MainInner(IRuntime rt)
    {
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

**Comment by jakobbotsch** [comment]
It's a weird issue that I unfortunately am unable to reproduce. I get:
```csharp
// Generated by Fuzzlyn v1.5 on 2022-04-01 11:00:58
// Run on X64 Windows
// Seed: 9461539929073564863
// Reduced from 347.0 KiB to 0.6 KiB in 00:01:50
// Debug: Outputs 1
// Release: Outputs 0
public struct S1
{
    public short F0;
    public long F1;
    public S1(long f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static void Main()
    {
        s_rt = new Runtime();
        var vr5 = new S1(1);
        M98(vr5);
    }

    public static void M98(S1 arg0)
    {
        ulong var15 = (ulong)((-arg0.F1) * -1);
        s_rt.WriteLine(var15);
    }
}

public interface IRuntime
{
    void WriteLine<T>(T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(T value) => System.Console.WriteLine(value);
}
```
This looks like the same as https://github.com/dotnet/runtime/issues/61074.

It seems to me the reduction process is somehow creating an invalid `Main` method in your case. Assuming you have `git.exe` on your path, can you please try passing `--reduce-debug-git-dir=<path to non-existant directory>` when you reduce the program? It will create a Git repository in that directory and commit every step of the reduction process in there. Then you can push that somewhere on GitHub, or just send me a .zip of it, and I can try to see if we do a wrong reduction at some point.

**Comment by bradmarder** [comment]
@jakobbotsch Very cool that it creates an entire git history for all the changes! Here it is, https://github.com/bradmarder/fuzz_debug

**Comment by jakobbotsch** [comment]
Are you disabling checksumming in your invocation to reduce the program?
This is not supported, disabling the checksumming is purely for outputting purposes. The checksumming is necessary for Fuzzlyn to know where the issue is/if there still is an issue.
I've added a sanity check in e523219eb23b169953bab07c494dceee9f21ed12.
