### ISSUE TITLE
Internal.Runtime.CompilerServices.Unsafe errors on Arm64

### ISSUE THREAD

**Issue by a74nh** [jakobbotsch/Fuzzlyn#14]
On Arm64 Linux Ubuntu 18.04 and a checkout/build of the latest dotnet/runtime.

Using Fuzzlyn with core_root (generated by ./src/tests/build.sh generatelayoutonly Checked ) everything is ok:
```
❯ /home/alahay01/dotnet/Fuzzlyn/publish/Fuzzlyn --seconds-to-run 180 --output-events-to issues-summary-Checked-None.txt --host /home/alahay01/dotnet/runtime_HEAD/artifacts/tests/coreclr/Linux.arm64.Checked/Tests/Core_Root/corerun --parallelism -1

00:00:49/00:03:00 elapsed, 200 programs generated, 0 examples found
00:01:08/00:03:00 elapsed, 100 programs generated, 0 examples found
00:02:01/00:03:00 elapsed, 300 programs generated, 0 examples found
00:02:10/00:03:00 elapsed, 400 programs generated, 0 examples found
00:02:57/00:03:00 elapsed, 500 programs generated, 0 examples found
^C
```

Using Fuzzlyn with the corerun in artifacts/bin then everything falls over. I get lots and lots of the same error with different seeds:
```
❯ /home/alahay01/dotnet/Fuzzlyn/publish/Fuzzlyn --seconds-to-run 180 --output-events-to issues-summary-Checked-None.txt --host /home/alahay01/dotnet/runtime_HEAD/artifacts/bin/coreclr/Linux.arm64.Checked/corerun --parallelism -1
Found example with seed 7417091245318271510 that hits error
Unhandled exception. System.TypeLoadException: Could not load type 'Internal.Runtime.CompilerServices.Unsafe' from assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
   at System.Buffers.Text.Base64.DecodeFromUtf8(ReadOnlySpan`1 utf8, Span`1 bytes, Int32& bytesConsumed, Int32& bytesWritten, Boolean isFinalBlock)
   at System.Text.Json.JsonReaderHelper.TryDecodeBase64(ReadOnlySpan`1 utf8Unescaped, Byte[]& bytes)
   at System.Text.Json.Utf8JsonReader.TryGetBytesFromBase64(Byte[]& value)
   at System.Text.Json.Utf8JsonReader.GetBytesFromBase64()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at Fuzzlyn.ExecutionServer.Program.<>c__DisplayClass0_0.<Main>b__0() in /home/alahay01/dotnet/Fuzzlyn/Fuzzlyn.ExecutionServer/Program.cs:line 48
```

**Comment by a74nh** [comment]
If it isn't supported running that way, then I'm ok with that :)

**Comment by jakobbotsch** [comment]
The directory under artifacts/bin just has the native bits and SPC. It is missing all other managed libraries, so indeed it is not going to work to run most managed apps under that. But you can set `CORE_ROOT` to point at where it should find the managed libraries:
```scala
./corerun --help
USAGE: corerun [OPTIONS] assembly [ARGUMENTS]

Execute the managed assembly with the passed in arguments

Options:
  -c, --clr-path - path to CoreCLR binary and managed CLR assemblies.
  -p, --property - Property to pass to runtime during initialization.
                   If a property value contains spaces, quote the entire argument.
                   May be supplied multiple times. Format: <key>=<value>.
  -d, --debug - causes corerun to wait for a debugger to attach before executing.
  -e, --env - path to a .env file with environment variables that corerun should set.
  -?, -h, --help - show this help.

The runtime binary is searched for in --clr-path, CORE_ROOT environment variable, then
in the directory the corerun binary is located.

Example:
Wait for a debugger to attach, provide 2 additional properties for .NET
runtime initialization, and pass an argument to the HelloWorld.dll assembly.
  corerun -d -p System.GC.Concurrent=true -p "FancyProp=/usr/first last/root" HelloWorld.dll arg1
```

**Comment by jakobbotsch** [comment]
Fuzzlyn runs an execution server under the host specified that communicates back and forth with the parent Fuzzlyn process, so it does have a few needed dependencies. I've thought about adding a mode that runs examples directly with the host to remove all non-SPC dependencies. That would probably work with even the corerun under artifacts/bin, but it would be much slower since it would incur runtime startup for every example.

**Comment by a74nh** [comment]
ok, that's fine, I'm happy with using a full core root
